
#!/usr/local/bin/python3

import csv

with open('tickets.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    col=1
    for row in reader:
        text='<div class="modal fade bd-example-modal-lg" id="exampleModal' + str(col) + '" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"> <div class="modal-dialog modal-lg" role="document"> <div class="modal-content"> <div class="modal-header"> <h5 class="modal-title" id="exampleModalLabel">New message</h5> <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span> </button> </div> <div class="modal-body" id="exampleModalBody"> <h1 style="text-align: center;"> <strong>1st Prize: $10,000</strong></h1> <h1 style="text-align: center;"> <strong>2nd Prize: $2,500</strong></h1> <h1 style="text-align: center;"> <strong>13 Prizes: $500.00</strong></h1> <h1 style="text-align: center;"> <strong>10 Prizes: $100.00</strong></h1> <div> &nbsp;</div> <ol> <li> $100.00 Per Ticket. Winner need not be present.</li> <li> All numbers will be drawn on September 24th, 2022 at the Mt. Sinai Fire Department, Station 1, 133 Mount Sinai Avenue.</li> <li> Gates will open at 1 pm and event will run until 5 pm, rain or shine.</li> <li> All winning numbers are re-entered for additional prizes.</li> <li> Only 2 ADULTS per ticket will be allowed entry. Please bring your own lawn chair.</li> <li> Only (up to) 500 tickets will be sold. Tickets must be shown at the gate for entry.</li> <li> No one under 21 will be admited. NO EXCEPTIONS!!!</li> <li> <strong>All tickets will be mailed to the address you put on the application once your check clears. Tickets purchased after 9/1/2022 can be picked up at the gate with photo ID.</strong></li> <li> You can choose your personal number 1-500. If a ticket number choice is not available, a random number will then be sent to you in its place.</li> <li> For additional questions contact: Cash Bash Committee at: msfdcashbash@gmail.com</li> <li> Entertainment, BBQ and drinks will be available during drawing, all included with ticket purchase.</li> </ol> <p> <strong>IF LESS THAN 500 TICKETS ARE SOLD, ALL PRIZES WILL BE PRO-RATED AT 60% OF TOTAL SOLD</strong></p> </div> <div id="smart-button-container"> <div style="text-align: center;"> <div style="margin-bottom: 1.25rem;"> <p>Ticket</p> <select id="item-options"><option value="Ticket" price="100.00">Ticket - 100.00 USD</option><option value="Ticket + Chance" price="105">Ticket + Chance - 105 USD</option></select> <select style="visibility: hidden" id="quantitySelect"></select> </div> <div id="paypal-button-container-' + str(col) + '"></div> </div> </div> <div class="modal-footer"> </div> </div> </div> </div> '
        col += 1
        print(text)
